name: cuflix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  screenshot: ^3.0.0
  http: ^1.2.1
  csv: ^6.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4     # latest at time of writing

flutter_launcher_icons:
  android: "launcher_icon"            # generate & overwrite
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21                 # recommended
  web:
    generate: true                    # optional
    background_color: "#000000"
    theme_color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/Image2.png
    - assets/Image3.png
    - assets/Image4.png
    - assets/Image5.png
    - assets/logo1.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        # The 'weight' property specifies the font weight. 400 is regular.
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700 # 700 is the weight for Bold